@extends('template.layout')
@section('content')

<div class="bocuc  bocuc_21 "><div class="loprong"><div class="padding "><div class="bocuc  bocuc_98  "><div class="loprong"><div class="padding "><p style="text-align: center;"><strong>Hãy liên hệ ngay tổng đài hoặc bạn có thể đăng ký Online bằng cách click đăng ký ở dưới để lắp đặt mạng wifi một cách nhanh nhất</strong></p>
    <p style="text-align: center;"><a title="Đăng ký Online" href="https://fpt.vn/sale/tunght" target="_blank" rel="noopener noreferrer"><strong><img src="files/assets/ng_k_ngay_400x110px_gif.gif" alt="ng_k_ngay_400x110px_gif" width="287" height="79"></strong></a></p></div></div></div><div class="bocuc  mauchitietbaiviet_1 bocuc_25  "><div class="loprong"><h1 class="header"><span class="header_text">Danh sách kênh mới nhất của Truyền Hình FPT liên tục cập nhật</span></h1><div class="padding ">    <div class="chucnang_chitiet likefacebook">	<div id="fb-root" class=" fb_reset"><div style="position: absolute; top: -10000px; width: 0px; height: 0px;"><div></div></div></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = 'https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.0&autoLogAppEvents=1';
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
     
    
    <div class="fb-like fb_iframe_widget" data-href="https://lapmangfpt.vn/danh-sach-kenh-truyen-hinh-fpt-bid448.html" data-layout="standard" data-action="like" data-size="small" data-show-faces="true" data-share="true" data-width="300px" fb-xfbml-state="rendered" fb-iframe-plugin-query="action=like&amp;app_id=&amp;container_width=820&amp;href=https%3A%2F%2Flapmangfpt.vn%2Fdanh-sach-kenh-truyen-hinh-fpt-bid448.html&amp;layout=standard&amp;locale=en_US&amp;sdk=joey&amp;share=true&amp;show_faces=true&amp;size=small&amp;width=300px"><span style="vertical-align: bottom; width: 300px; height: 20px;"><iframe name="f4c31bec15cc5d689" height="1000px" data-testid="fb:like Facebook Social Plugin" title="fb:like Facebook Social Plugin" frameborder="0" allowtransparency="true" allowfullscreen="true" scrolling="no" allow="encrypted-media" src="https://web.facebook.com/v3.0/plugins/like.php?action=like&amp;app_id=&amp;channel=https%3A%2F%2Fstaticxx.facebook.com%2Fx%2Fconnect%2Fxd_arbiter%2F%3Fversion%3D46%23cb%3Dfa06f0b6d864b3823%26domain%3Dlapmangfpt.vn%26is_canvas%3Dfalse%26origin%3Dhttps%253A%252F%252Flapmangfpt.vn%252Ffad03beaa1eab3510%26relation%3Dparent.parent&amp;container_width=820&amp;href=https%3A%2F%2Flapmangfpt.vn%2Fdanh-sach-kenh-truyen-hinh-fpt-bid448.html&amp;layout=standard&amp;locale=en_US&amp;sdk=joey&amp;share=true&amp;show_faces=true&amp;size=small&amp;width=300px" style="border: none; visibility: visible; width: 300px; height: 20px;" class=""></iframe></span></div>
    </div><div class="chucnang_chitiet noidungchitiet"> <span class="giatri"><h2 style="text-align: center;">Bảng Danh sách kênh của Truyền Hình FPT 2024</h2><p><a data-mce-href="truyen-hinh-fpt-bid7.html" href="truyen-hinh-fpt-bid7.html" target="_blank" rel="noopener noreferrer" title="Truyền hình FPT">Truyền hình FPT</a> gồm hơn 170 kênh (trong đó có gần 50 kênh HD) với chất lượng hình ảnh và âm thanh sắc nét sống động, được chia làm hai gói kênh: gói Cơ bản và gói Mở rộng.</p><p>1.Gói Cơ Bản</p><p><a data-mce-href="goi-cuoc-co-ban-truyen-hinh-fpt-bid446.html" href="goi-cuoc-co-ban-truyen-hinh-fpt-bid446.html" title="Gói Cơ bản"><strong>Gói Cơ bản</strong></a>&nbsp;đa dạng nhóm kênh: VTV, HTV, VTC, kênh tổng hợp, phim truyện, giải trí, hoạt hình, thể thao, âm nhạc, tin tức, kênh địa phương, kênh chuyên biệt….</p><p><img style="float: none; display: block; margin-left: auto; margin-right: auto;" src="files/assets/danh_sach_kenh_1.jpg" alt="danh_sach_kenh_1" data-mce-src="files/assets/danh_sach_kenh_1.jpg" width="578" height="817"><br></p><p>2.Gói Mở Rộng</p><p><a data-mce-href="goi-mo-rong-truyen-hinh-fpt-bid447.html" href="goi-mo-rong-truyen-hinh-fpt-bid447.html" title="Gói Mở rộng"><strong>Gói Mở rộng</strong></a>&nbsp;bao gồm gói Đặc sắc, K+, Ngoại hạng Anh… phù hợp với nhu cầu thưởng thức của nhiều đối tượng khán giả</p><p><img style="float: none; display: block; margin-left: auto; margin-right: auto;" src="files/assets/danh_sach_kenh_2.jpg" alt="danh_sach_kenh_2" data-mce-src="files/assets/danh_sach_kenh_2.jpg" width="581" height="821"><br></p><p><strong>Những tính năng thông minh vượt trội của Truyền hình FPT:</strong></p><ul><li><strong>Truyền hình xem lại</strong>: giúp người dùng chủ động xem lại những chương trình đã phát mà mình bỏ lỡ trước đó.</li><li><strong>Giám sát trẻ em</strong>: giúp các bậc phụ huynh dễ dàng thiết lập và quản lý nội dung xem của trẻ theo độ tuổi và thời gian thông qua mật khẩu.</li><li><strong>Lịch phát sóng tổng hợp (EPG)</strong>: cho phép người dùng được xem trước lịch phát sóng của một số kênh truyền hình được hỗ trợ. Đặc biệt, khi sử dụng tính năng Cài đặt hẹn giờ, hệ thống sẽ tự động thông báo để khán giả tiện theo dõi.</li><li><strong>Tùy chỉnh ngôn ngữ</strong>: cho phép người dùng bật/tắt thuyết minh, phụ đề tiếng Việt hoặc ngôn ngữ gốc của nhiều kênh truyền hình quốc tế.</li><li><strong>Lưu yêu thích</strong>: là tính năng giúp khán giả có thể lưu các kênh, các chương trình mà mình yêu thích.</li><li><img style="float: none; display: block; margin-left: auto; margin-right: auto;" src="files/assets/sdt_hotline_new2.png" alt="sdt_hotline_new2" width="383" height="108" data-mce-src="files/assets/sdt_hotline_new2.png"></li></ul></span></div><style></style></div></div></div></div></div></div>
@endsection